### PR TITLE
Add environment variable to disable redis cache

### PR DESCRIPTION
**Pull request by csolem**
Makes it possible to disable the redis cache by using an environmental variable: _IEV_DISABLE_CACHE_

For the reference, see https://github.com/afimb/ievkit_views/pull/1

### CODE REVIEW

**Comment by brunto** [comment]
Hi,
I think it will be a good thing to keep a way to disable manually the cache for a specific request.
We could have two options : 
1. Globally disable cache with ENV variable
2. Keep the cache enabled and disable it for a specific request

**Comment by brunto** [comment]
I have merged you PR and keep the way to manually disable cache.
You can check it here: https://github.com/afimb/ievkit/commit/49c7d88d863180cb82971fef7e70fb057b6b7908

**Comment by csolem** [comment]
Thanks @brunto. Will my changes be merged to develop or master?

**Comment by brunto** [comment]
I will merge your pull request inside develop today.

**Pull request closed without merging**
